// leave off @2x/@3x
const images = {
    cover_bg_1 : require('./Images/cover_bg_1.png'),
    cover_bg_2 : require('./Images/cover_bg_2.png'),
    cover_bg_3 : require('./Images/cover_bg_3.png'),
    cover_bg_4 : require('./Images/cover_bg_4.png'),
    sinup_btn : require('./Images/signup_btn.png'),
    login_btn : require('./Images/login_btn.png'),
    facebook_signup_btn : require('./Images/facebook_signup_btn.png'),
    sinup_btn1 : require('./Images/signup_btn1.png'),
    password_icon :require('./Images/password_icon.png'),
    trick_icon :require('./Images/trick_icon.png'),
    v_icon :require('./Images/v_icon.png'),
    placeholderImg : require('./Images/placeholder.png'),
    avatar_edit_btn : require('./Images/avatar_edit_btn.png'),
    login_bg : require('./Images/login_bg.png'),
    login_btn1 : require('./Images/login_btn1.png'),
    rigister_btn : require('./Images/register_btn.png'),
    ready_btn : require('./Images/ready_btn.png'),
    addcoffee_bg: require('./Images/addcoffee_bg.png'),
    coffee_icon : require('./Images/coffee.png'),
    bean_icon : require('./Images/bean.png'),
    item_icon : require('./Images/item_icon.png'),
    send_request_btn : require('./Images/send_request_btn.png'),
    close_btn : require('./Images/close_btn.png'),
    arrow_icon: require('./Images/arrow_icon.png'),
    i_icon: require('./Images/i_icon.png'),
    userprofile_1: require('./Images/userprofile_1.png'),
    userprofile_2: require('./Images/userprofile_2.png'),
    userprofile_3: require('./Images/userprofile_3.png'),
    recipe_1_selected: require('./Images/recipe_1_selected.png'),
    recipe_1_unselected: require('./Images/recipe_1_unselected.png'),
    recipe_2_selected: require('./Images/recipe_2_selected.png'),
    recipe_2_unselected: require('./Images/recipe_2_unselected.png'),
    recipe_3_selected: require('./Images/recipe_3_selected.png'),
    recipe_3_unselected: require('./Images/recipe_3_unselected.png'),
    recipe_4_selected: require('./Images/recipe_4_selected.png'),
    recipe_4_unselected: require('./Images/recipe_4_unselected.png'),
    line_selected: require('./Images/line_selected.png'),
    line_unselected: require('./Images/line_unselected.png'),
    confirm_btn: require('./Images/confirm_btn.png'),
    brew_bg :require('./Images/brew_bg.png'),
    recipe_content :require('./Images/recipe_content.png'),
    brew_now_btn :require('./Images/brew_now_btn.png'),
    coffee_icon2 :require('./Images/coffee_icon.png'),
    product :require('./Images/product.png'),
    scrolldown_btn :require('./Images/scrolldown_btn.png'),
    scrollUp_btn :require('./Images/scrollup_btn.png'), 
    setting_btn :require('./Images/setting_btn.png'),

    recipe_content_1 :require('./Images/recipe_contents/recipe_content_1_extend.png'),
    recipe_content_2 :require('./Images/recipe_contents/recipe_content_2.png'),
    recipe_content_3 :require('./Images/recipe_contents/recipe_content_3.png'),
    recipe_content_4 :require('./Images/recipe_contents/recipe_content_4.png'),
    recipe_content_5 :require('./Images/recipe_contents/recipe_content_5.png'),
    edit_recipe_btn :require('./Images/recipe_contents/edit_recipe_btn.png'),
    create_recipe_btn :require('./Images/recipe_contents/create_recipe_btn.png'),
    brewing_bg :require('./Images/brew_bgs/brew_bg.png'),
    product_1 :require('./Images/brew_bgs/product_1.png'),
    product_2 :require('./Images/brew_bgs/product_2.png'),
    product_3 :require('./Images/brew_bgs/product_3.png'),
    progress_line_1:require('./Images/brew_bgs/progress_line_1.png'),
    progress_line_2:require('./Images/brew_bgs/progress_line_2.png'),
    progress_line_3:require('./Images/brew_bgs/progress_line_3.png'),
    customize_recipe_btn :require('./Images/customize_recipe_btn.png'),
    customerize_content :require('./Images/customerize_content.png'),
    close_btn1 :require('./Images/close_btn1.png'),
}

export default images
